### ISSUE TITLE
Checkpoint download

### ISSUE THREAD

**Issue by xvjiarui** [kiranchhatre/amuse#4]
Hi Kiran, 

Congrats to the amazing "amuse"! Cheers on the code release as well. 
As we are trying to run the inference, we found the checkpoint is not available yet. 

The checkpoints here require password to download. 
> Checkpoints:
> lpdm and prior checkpoint: $AMUSEPATH/saved-models/foldername from [Keeper link](https://keeper.mpdl.mpg.de/d/4d2b6cd19aac420fa895/)
> audio checkpoint: $AMUSEPATH/saved-models/foldername from [Keeper link](https://keeper.mpdl.mpg.de/d/dd470f22d7684ae78cf7/)

Could you please take a look? Thank you so much!

Best,
Jiarui

**Comment by kiranchhatre** [comment]
Hi Jiarui,

Thank you for your kind words. 
Regarding the checkpoints, please look for the password on the top left of the download page, below the "Data Setup" section.

Best,
Kiran

**Comment by xvjiarui** [comment]
Thank you so much!

**Comment by ylhua** [comment]
> Thank you so much!

Hi, have you successfully built the environment?
